# Generated by Django 4.2.1 on 2023-07-02 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appsoftdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
