# Generated by Django 4.2.1 on 2023-07-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsoftdesk', '0002_alter_contributors_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributors', to='appsoftdesk.projects'),
        ),
    ]
