# Generated by Django 4.2.1 on 2023-07-16 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsoftdesk', '0005_alter_comments_issue_alter_issues_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='appsoftdesk.projects'),
        ),
    ]
